# Generated by Django 4.0.3 on 2022-03-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapps', '0002_rename_address_customer_address_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
